import { Poppins } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'

const inter = Poppins({ weight:'500', subsets: ['latin'] })

export const metadata = {
  title: 'React Workflow Builder',
  description: 'Generated by NextJs',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
